### ISSUE TITLE
Allow enabling user authentication with Kerberos

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/hbase-operator#285]
As a user/admin I'd like to be able to enable user authentication using Kerberos in HBase so I can authenticate all requests.

Current working branch: https://github.com/stackabletech/hbase-operator/tree/feat/kerberos-reloaded

This is done when

- [x] a CRD change(s) has been proposed and reviewed on how to enable Kerberos this should be aligned with https://github.com/stackabletech/hdfs-operator/issues/178
- [x]  it uses the functionality provided by the secret operator to provision Kerberos keytabs https://github.com/stackabletech/secret-operator/issues/4
- [x]  documentation is added
- [x]  integration tests are added
- [x]  feature tracker is updated

**Comment by sbernauer** [comment]
This is blocked by https://github.com/stackabletech/hbase-operator/issues/352, unless we want to build hbase 2.4 with hadoop3 and ship that (we need hadoop3 because we use hdfs 3 and otherwise things are failing randomly)
