### ISSUE TITLE
Operator constructs the configmap incorrectly

### ISSUE THREAD

**Issue by zaultooz** [stackabletech/hbase-operator#393]
### Affected version

23.7.0

### Current and expected behavior

Hey Stackable

While I was upgrading to the new release 23.7.0, I spotted a problem during the rolling start of the hbase master. It seems to try and create a node in Zookeeper on *//hbase*. The master reports this is a problem as it expects a string between the two forward slashes.

Looking at the configmaps I can see the property describing the root folder in zookeeper being set to:
```
zookeeper.znode.parent: //hbase
```

Trying to use the *configOverrides* option result in no changes to the property so I suspect the operator doesn't pick the correct values when creating this specific property in the hbase-site.xml file.

### Possible solution

I haven't looks at the source so I don't have any good suggestions solution to the concrete changes needed for resolving the issue.

### Additional context

Rolling the CRD and operator back to 23.4.1 seems to result in the correct behavior.

### Environment

Client Version: v1.25.5
Kustomize Version: v4.5.7
Server Version: v1.25.5

### Would you like to work on fixing this bug?

maybe

**Comment by Jimvin** [comment]
Hi,
This looks like the ZooKeeper znode is not being set. When created, the znode should appear in ZooKeeper in it's own path named /<uuid>/, and HBase creates it's znodes under /<uuid>/hbase. The double slash suggests that the znode is not appearing in the HBase configuration. Can I ask you to check/confirm a few things please:

- What Kubernetes distribution/platform are you using? Is this for example public cloud hosted Kubernetes e.g. AKS on Amazon? 
- Have you created a ZookeeperZnode as described in the Stackable docs? https://docs.stackable.tech/home/stable/hbase/getting_started/first_steps
- If you have created the Znode is this referenced correctly in the zookeeperConfigMapName property of your HBase definition?

Kind regards,
Jim

**Comment by sbernauer** [comment]
@zaultooz although not recommend this should work (as it has worked in the past) - recommended way would be to use ZNodes (see https://docs.stackable.tech/home/stable/hbase/getting_started/first_steps)

Created a fix: https://github.com/stackabletech/hbase-operator/pull/394

**Comment by zaultooz** [comment]
Thanks @sbernauer  and @Jimvin, we already have a zookeeper and znode running in our self hosted cluster. However I can see I have been pointing the zookeeper-cluster CM and not the zookeeper-cluster-znode CM, so I will be retesting the 23.7 version pointing to the proper CM.

**Comment by zaultooz** [comment]
Pointing to the zookeeper-cluster-znode configmap results in the operator creating the configmap pointing to a valid root without the need to overwrite it. 

Thanks for the help :)
