### ISSUE TITLE
Add hbck2 tool to the hbase master image

### ISSUE THREAD

**Issue by alexsteeel** [stackabletech/hbase-operator#474]
Please consider adding the hbck2 tool to the hbase master image.

Description of tool:
- [Apache HBase HBCK2 Tool](https://github.com/apache/hbase-operator-tools/blob/master/hbase-hbck2/README.md)
- [Use the Apache HBase HBCK2 tool]( https://learn.microsoft.com/en-us/azure/hdinsight/hbase/how-to-use-hbck2-tool)

Message from hbase master logs after file system recovery with link to this tool:

> ERROR [master/hbase-master-default-0:16000:becomeActiveMaster] master.HMaster: Failed to become active master
> org.apache.hadoop.hbase.util.FileSystemVersionException: hbase.version file is missing. Is your hbase.rootdir valid? You can restore hbase.version file by running 'HBCK2 filesystem -fix'. See https://github.com/apache/hbase-operator-tools/tree/master/hbase-hbck2
>         at org.apache.hadoop.hbase.util.FSUtils.checkVersion(FSUtils.java:433)
>         at org.apache.hadoop.hbase.master.MasterFileSystem.checkRootDir(MasterFileSystem.java:275)
>         at org.apache.hadoop.hbase.master.MasterFileSystem.createInitialFileSystemLayout(MasterFileSystem.java:145)
>         at org.apache.hadoop.hbase.master.MasterFileSystem.<init>(MasterFileSystem.java:115)
>         at org.apache.hadoop.hbase.master.HMaster.finishActiveMasterInitialization(HMaster.java:806)
>         at org.apache.hadoop.hbase.master.HMaster.startActiveMasterManager(HMaster.java:2184)
>         at org.apache.hadoop.hbase.master.HMaster.lambda$run$0(HMaster.java:519)
>         at java.base/java.lang.Thread.run(Thread.java:829)

I tried to start the first version of hbck
`/stackable/hbase-2.4.12/bin/hbase hbck -details`
but got an error message:

> WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
> Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/bridge/SLF4JBridgeHandler
>         at org.apache.hadoop.hbase.logging.JulToSlf4jInitializer.<clinit>(JulToSlf4jInitializer.java:36)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
>         at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
>         at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
>         at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
>         at java.base/java.lang.Class.newInstance(Class.java:584)
> 	...

**Comment by alexsteeel** [comment]
Sorry, I found this tool in a new version of the image:
https://github.com/stackabletech/docker-images/blob/main/hbase/Dockerfile#L66

**Comment by lfrancke** [comment]
Hi,

hbck2 is included in our image already as of our release 23.11:

- https://docs.stackable.tech/home/stable/hbase/usage-guide/operations/cluster-operations
- https://github.com/stackabletech/docker-images/issues/359
- https://github.com/stackabletech/docker-images/blob/main/hbase/Dockerfile#L52-L72

You should be able to find everything you need in `/stackable/hbase-operator-tools`

I hope that helps!

**Comment by alexsteeel** [comment]
> Hi,
> 
> hbck2 is included in our image already as of our release 23.11:
> 
> * https://docs.stackable.tech/home/stable/hbase/usage-guide/operations/cluster-operations
> * [Add HBCK2 to the HBase images docker-images#359](https://github.com/stackabletech/docker-images/issues/359)
> * https://github.com/stackabletech/docker-images/blob/main/hbase/Dockerfile#L52-L72
> 
> You should be able to find everything you need in `/stackable/hbase-operator-tools`
> 
> I hope that helps!

Thanks for the help and links!
